import {Check,Plus,ArrowUpRight,Lock,ArrowRight,Mail,FileText,Users,Link2,CheckCheck} from 'lucide-react';
import type {Pattern} from './catalog';
export default function Thumbnail({p}:{p:Pattern}){
 const type=p.kind;
 let inner;
 if(['pricing','annual','downgrade','seat','billing','addon'].includes(type))inner=<div className="thumb-pricing"><div className="thumb-toggle"><span>Monthly</span><b>Yearly <i>−20%</i></b></div><div className="thumb-plan-row">{['Starter','Team','Business'].map((x,i)=><div className={i===1?'chosen':''} key={x}><small>{x}</small><strong>${[0,19,49][i]}<em>/mo</em></strong><span/><span/><span/>{i===1?<b>Choose Team <ArrowRight size={9}/></b>:<b>Get started</b>}</div>)}</div></div>;
 else if(['calculator','goal','limit'].includes(type))inner=<div className="thumb-calculator"><div className="thumb-line"><span>{type==='calculator'?'Team size':'Weekly progress'}</span><b>{type==='calculator'?'24 people':'8 of 12'}</b></div><div className="thumb-slider"><i/></div><div className="thumb-line"><span>{type==='calculator'?'Hours saved / week':'Team handoffs'}</span><b>{type==='calculator'?'3 hours':'67%'}</b></div><div className="thumb-slider short"><i/></div><div className="thumb-result"><small>{type==='calculator'?'POTENTIAL ANNUAL VALUE':'MOVING IN THE RIGHT DIRECTION'}</small><strong>{type==='calculator'?'$155,520':'A little further, every day.'}</strong><span>{type==='calculator'?'3,456 hours back to your team':'4 more handoffs to your weekly goal'}</span></div></div>;
 else if(['checklist','milestone','reward','trial'].includes(type))inner=<div className="thumb-checklist"><div className="thumb-line"><strong>{type==='milestone'?'Good work adds up.':'Your first win starts here.'}</strong><span>2 / 4</span></div><div className="thumb-progress"><i/></div>{p.items.slice(0,4).map((x,i)=><div className="thumb-check-row" key={x}><span className={i<2?'checked':''}>{i<2&&<Check size={9}/>}</span><small>{x}</small>{i===2&&<ArrowUpRight size={11}/>}</div>)}</div>;
 else if(['template','create','winback'].includes(type))inner=<div className="thumb-board"><div className="thumb-line"><strong>{p.items[0]}</strong><Plus size={12}/></div><div className="thumb-columns">{['To do','In progress','Done'].map((x,i)=><div key={x}><small><i/>{x}</small>{[0,1,2].slice(0,i===1?2:3).map(n=><div className="thumb-task" key={n}><span/><span/><b>{i===2?<Check size={8}/>:<i/>}</b></div>)}</div>)}</div></div>;
 else if(['connect','import','search'].includes(type))inner=<div className="thumb-connections"><strong>{type==='connect'?'Your tools, working together.':type==='import'?'Bring your work with you.':'A little closer to your team.'}</strong>{(type==='connect'?p.items:['Acme Design','Acme Operations','Acme Growth']).slice(0,3).map((x,i)=><div key={x}><span>{x[0]}</span><small>{x}</small><b>{i===0?<><Check size={9}/>Connected</>:'Connect'}</b></div>)}</div>;
 else if(['paywall','upgrade','share'].includes(type))inner=<div className="thumb-chart"><div className="thumb-line"><strong>Team performance</strong><small>This month ↗</small></div><div className="thumb-bars">{[25,42,37,61,52,72,82,76,92].map((n,i)=><i key={i} style={{height:n+'%'}}/>)}</div><div className="thumb-chart-foot"><Lock size={10}/><span>Unlock a clearer picture</span><ArrowRight size={11}/></div></div>;
 else if(['notification','digest','segment'].includes(type))inner=<div className="thumb-settings"><div className="thumb-line"><strong>Your workspace. Your rhythm.</strong><Mail size={13}/></div>{p.items.slice(0,3).map((x,i)=><div key={x}><span><small>{x}</small><i/></span><b className={i===0?'on':''}/></div>)}<div className="thumb-save">Save preferences<Check size={10}/></div></div>;
 else if(['invite','referral'].includes(type))inner=<div className="thumb-invite"><div className="thumb-avatars">{['A','S','J'].map(x=><b key={x}>{x}</b>)}<span>+</span></div><strong>{type==='referral'?'Good tools are better shared.':'Better work, together.'}</strong><small>A little invitation. A lot of possibility.</small><div><span>{type==='referral'?'atlas.example/r/acme':'teammate@company.com'}</span><ArrowRight size={12}/></div><p>Make room for your next great collaboration.</p></div>;
 else if(['quiz','feedback','survey','cancel','pause'].includes(type))inner=<div className="thumb-choices"><strong>{p.headline}</strong>{p.items.slice(0,3).map((x,i)=><div className={i===1?'selected':''} key={x}><i>{i===1&&<span/>}</i><small>{x}</small>{i===1&&<Check size={11}/>}</div>)}<b>Continue<ArrowRight size={11}/></b></div>;
 else inner=<div className="thumb-form"><div className="thumb-step"><b>1</b><i/><span>2</span><i/><span>3</span></div><strong>{p.headline}</strong><small>{p.items[0]}</small><div>you@company.com<span/></div><small>{p.items[1]||'Workspace name'}</small><div>Acme workspace</div><b>Continue<ArrowRight size={11}/></b></div>;
 return <div className={`thumbnail thumbnail-${p.kind}`} aria-hidden="true"><div className="thumb-window"><div className="thumb-window-top"><span className="thumb-logo">a.</span><span>acme workspace</span><i/><i/><i/></div>{inner}</div><span className="thumbnail-tag">{p.format==='Flow'?<><span>01</span><i/><span>02</span><i/><span>03</span></>:<><span className="live-dot"/>Interactive preview</>}</span></div>
}
